language: node_js
node_js:
  - lts/*
env:
  - EXTENSION_ID=menecfddnlmanmpadcalononkolnplpp
jobs:
  include:
    - stage: deploy
      script: npm run build
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
stages:
  - name: deploy
    if: branch = master AND commit_message =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/
