language: node_js
node_js:
  - lts/*
env:
  - EXTENSION_ID=menecfddnlmanmpadcalononkolnplpp
script:
  - npm run build
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
stages:
  - name: deploy
    if: commit_message = /^\d+\.\d+(\.\d+)?(-\S*)?$/
