language: node_js
node_js:
  - lts/*
env:
  - WEXT_SHIPIT_CHROME_EXTENSION_ID=menecfddnlmanmpadcalononkolnplpp WEXT_SHIPIT_FIREFOX_EXTENSION_ID={adc96546-ad4d-4b76-9df3-84cdd73af6fa} WEXT_SHIPIT_OPERA_EXTENSION_ID=245385
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: deploy
      script: npm run package:webext
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release:chrome
    - stage: deploy
      script: npm run package:webext
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release:firefox
    - stage: deploy
      script: npm run package:webext
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release:opera
stages:
  - build
  - name: deploy
    if: branch = master AND commit_message =~ /v?\d+\.\d+(\.\d+)?(-\S*)?$/
